version: "3.8"

# docker exec -it a54b8ca14639 bash -c "psql -U root -d simulador"
services:
  postgres:
    image: 'postgres:14.1-alpine'
    container_name: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simulador
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

